version: '3'

services:
  web:
    build: ./app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - ./db-data:/data/db